version: '2'

volumes:
  inbox-postgres: {}
  inbox-postgres-backup: {}
  inbox-django-media: {}
  inbox-django-static: {}

services:
  clamav:
    image: scieloorg/inbox_clamav
    ports:
      - 3310/tcp
    labels:
      io.rancher.container.pull_image: always

  postgres:
    image: scieloorg/inbox_postgres
    environment:
      - POSTGRES_PASSWORD=
      - POSTGRES_USER=postgres
    volumes:
      - inbox-postgres:/var/lib/postgresql/data
      - inbox-postgres-backup:/backups
    ports:
      - 5432/tcp
    labels:
      io.rancher.container.pull_image: always

  redis:
    image: redis:latest
    labels:
      io.rancher.container.pull_image: always

  nginx:
    image: scieloorg/inbox_nginx
    volumes:
      - inbox-django-static:/static
      - inbox-django-media:/media
    links:
      - django
    ports:
      - 80:80

  django:
    image: scieloorg/inbox
    environment:
      - CLAMAV_HOST:clamav
      - CLAMAV_PORT=3310
      - DJANGO_ACCOUNT_ALLOW_REGISTRATION=true
      - DJANGO_ADMIN_URL=
      - DJANGO_ALLOWED_HOSTS=*
      - DJANGO_MAILGUN_API_KEY=
      - DJANGO_SECRET_KEY=e&@q(%h-6^r-+y7(d@x3)9#0gzq7p6-x=8nn+s#u2#^5+d_@ut
      - DJANGO_SECURE_SSL_REDIRECT=false
      - DJANGO_SERVER_EMAIL=
      - DJANGO_SETTINGS_MODULE=config.settings.production
      - POSTGRES_PASSWORD=
      - POSTGRES_USER=postgres
    ports:
      - 5000:5000
    user: django
    command:
      - /gunicorn.sh
    links:
      - postgres
    volumes:
      - inbox-django-media:/app/media
      - inbox-django-static:/app/static
    labels:
      io.rancher.container.pull_image: always

  celeryworker:
    image: scieloorg/inbox
    environment:
      - CLAMAV_HOST:clamav
      - CLAMAV_PORT=3310
      - DJANGO_ACCOUNT_ALLOW_REGISTRATION=true
      - DJANGO_ADMIN_URL=
      - DJANGO_ALLOWED_HOSTS=*
      - DJANGO_MAILGUN_API_KEY=
      - DJANGO_SECRET_KEY=e&@q(%h-6^r-+y7(d@x3)9#0gzq7p6-x=8nn+s#u2#^5+d_@ut
      - DJANGO_SECURE_SSL_REDIRECT=false
      - DJANGO_SERVER_EMAIL=
      - DJANGO_SETTINGS_MODULE=config.settings.production
      - POSTGRES_PASSWORD=
      - POSTGRES_USER=postgres
    volumes:
      - inbox-django-media:/app/media
    links:
      - clamav:clamav
      - redis:redis
      - postgres:postgres
    user: django
    command:
      - celery -A inbox.taskapp worker -l INFO
    labels:
      io.rancher.container.pull_image: always

  celerybeat:
    image: scieloorg/inbox
    environment:
      - CLAMAV_HOST:clamav
      - CLAMAV_PORT=3310
      - DJANGO_ACCOUNT_ALLOW_REGISTRATION=true
      - DJANGO_ADMIN_URL=
      - DJANGO_ALLOWED_HOSTS=*
      - DJANGO_MAILGUN_API_KEY=
      - DJANGO_SECRET_KEY=e&@q(%h-6^r-+y7(d@x3)9#0gzq7p6-x=8nn+s#u2#^5+d_@ut
      - DJANGO_SECURE_SSL_REDIRECT=false
      - DJANGO_SERVER_EMAIL=
      - DJANGO_SETTINGS_MODULE=config.settings.production
      - POSTGRES_PASSWORD=
      - POSTGRES_USER=postgres
    volumes:
      - inbox-django-media:/app/media
    links:
      - clamav:clamav
      - redis:redis
      - postgres:postgres
    user: django
    command:
      - celery -A inbox.taskapp beat -l INFO
    labels:
      io.rancher.container.pull_image: always
